config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'archives/index'
  root to: 'entries#index'
  resources :entries

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :entries
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :calories, :proteins, :carbohydrates, :fats, :meal_type, :category_id, presence: :true
  belongs_to :category

  def day 
    self.created_at.strftime("%b %e, %Y")
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
      @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.where("created_at >= ?", Date.today)
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered">
  <div class="column is-half">
    <% @entries.each do |day, entries| %>
      <div class="mt-6">
      <h3 class="is-size-4 has-text-weight-bold has-text-centered">
        Entries for <%= day%>
      </h3>

      <nav class="level is-mobile">
        <div class="level-item has-text-center">
          <div> 
            <p class="heading">Calories</p>
            <p class="title"><%= entries.pluck(:calories).sum%></p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div> 
            <p class="heading">Protein</p>
            <p class="title"><%= entries.pluck(:proteins).sum%>g</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div> 
            <p class="heading">Carbohydrates</p>
            <p class="title"><%= entries.pluck(:carbohydrates).sum%>g</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div> 
            <p class="heading">Fats</p>
            <p class="title"><%= entries.pluck(:fats).sum%>g</p>
          </div>
        </div>
      </nav>

       <% entries.each do | entry | %>
        <%= link_to entry_path(entry) do %>
          <div class="card">
            <div class="card-content">
              <strong><%= entry.meal_type %></strong><br/>
              <%= entry.calories %> calories,
              <%= entry.proteins %>g protein,
              <%= entry.carbohydrates %>g carbs,
              <%= entry.fats %>g fat
            </div>
          </div>
        <% end %>
       <% end %>
       </div>
    <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>
      <div class="message-body">
        <ul>
          <% entry.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal_type, class: "label" %>
    <%= form.text_field :meal_type, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :category_id, class: "label" %>
    <div class="select">
      <%= form.select :category_id, Category.all.collect {|u| [u.title, u.id]}, {}%>
    </div>
  </div>

  <div class="field">
    <%= form.label :calories, class: "label" %>
    <%= form.number_field :calories, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :proteins, class: "label" %>
    <%= form.text_field :proteins, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :carbohydrates, class: "label" %>
    <%= form.number_field :carbohydrates, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :fats, class: "label" %>
    <%= form.number_field :fats, class: "input" %>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-success" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-3 has-text-weight-bold mb-3">Editing Entry</h1>
    <%= render 'form', entry: @entry %>
  </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Foodlog &ndash; <%= DateTime.now.to_s(:nice_date)%>
<% end %>

<div class="columns mt-6 is-centered">
  <% @entries.each do |entry| %>
    <div class="column is-one-quarter">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title"><%= entry.meal_type %> - <%= entry.category.title if entry.category.present? %></p>
        </header>
        <div class="card-content">
          <div class="content">
            <p><span class="has-text-weight-bold"><%= entry.calories %></span> calories</p>
            <p><span class="has-text-weight-bold"><%= entry.proteins %></span> grams of protein</p>
            <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> grams of carbohydrates</p>
            <p><span class="has-text-weight-bold"><%= entry.fats %></span> grams of fat</p>
            <p class="italic">Logged <%= time_ago_in_words(entry.created_at) %> ago</p>
          </div>
        </div>
      <div class="card-footer">
        <%= link_to 'Show', entry, class: "card-footer-item" %>
        <%= link_to 'Edit', edit_entry_path(entry), class: "card-footer-item" %>
        <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-footer-item" %>
      </div>
      
    </div>
    </div>
  <% end %>
</div>

<div class="columns is-centered mt-6">
  <%= link_to "View all entries", archives_index_path, class: "button is-link is-outlines is-centered" %>
</div>

app/views/entries/new.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-3 has-text-weight-bold mb-3">New Entry</h1>
    <%= render 'form', entry: @entry %>
  </div>
</div>

app/views/entries/show.html.erb
<% content_for :title do%>
  <%= @entry.meal_type %> &ndash; <%= DateTime.now.to_s(:nice_date)%>
<% end %>

<div class="columns mt-6 is-centered">
  <div class="column is-one-third">
    <nav class="panel is-link">
      <p class="panel-heading">
        <%= @entry.meal_type %>
      </p>

      <div class="panel-block">
        Calories: <%= @entry.calories %>
      </div>
      
      <div class="panel-block">
      Proteins: <%= @entry.proteins %>
      </div>

      <div class="panel-block">
      Carbohydrates: <%= @entry.carbohydrates %>
      </div>

      <div class="panel-block">
        Fats: <%= @entry.fats %>
      </div>
  </nav>

<div class="columns is-mobile">
  <div class="column">
      <%= link_to "Edit", edit_entry_path(@entry), class: "button is-gray" %>
      <%= link_to "Delete", entries_path(@entry), method: :delete,data: {confirm: "Are you sure?"}, class: "button is-gray" %>
    </div>
    <div class="column">
    </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "shared/header" %>
  <% if notice.present? %>
    <p class="notification is-link is-light" id="notice"><%= notice %></p>
  <% end %>

  <% if alert.present? %>
    <p class="notification is-danger is-light" id="notice"><%= alert %></p>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-link is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          
            <%= link_to root_path, class: "navbar-item" do%>
              <span class="has-text-weight-bold is-size-4 ml-4">Foodlog</span>
            <% end %>
          
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
              <%= link_to "Create new entry",  new_entry_path, class: "button is-success"%>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        <% if content_for(:title) %>
          <%= yield :title %>
        <% else %>
          Foodlog
        <% end %>
      </p>
    </div>
  </div>
</section>